### ISSUE TITLE
Makeing an outbound call

### ISSUE THREAD

**Issue by infosteo** [AsterNET/AsterNET#262] opened 2021-12-15 09:42 UTC
Hello,
I'm trying to originate an outbound call but the call starts, the internal ip phone rings but external line is not connected.
Here is the source:
```C#
OriginateAction ox = new OriginateAction();
ox.Priority = "1";
ox.Exten = "03xxxx";  //external numer to call
ox.CallerId = "01xxxxx"; //this is the external line number of my pbx
ox.Context = "from-internal"; 
ox.Channel = "SIP/trunk/yyyy"; //yyyy is my internal phone number
ox.Timeout = 30000;
ox.Async = true;
ManagerResponse mr = manager.SendAction(ox, ox.Timeout);
```

I also tried to add, before `SendAction`:
```C#
ox.Application = "Dial";
ox.Data = "SIP/trunk/yyyy extension 03xxxxx@from-internal";
```

What am I Doing wrong?

Thank you
Stefano

**Comment by Deantwo** [comment] 2021-12-18 16:19
Duplicate of #18

**Comment by Deantwo** [comment] 2021-12-18 16:30
Edited example from #18:
```C#
OriginateAction oc = new OriginateAction();
oc.Priority = "1";
oc.Exten = "03xxxx";  // extension to call
oc.CallerId = "01xxxxx"; // CallerID used by the PBX to agent
oc.Context = "from-internal"; // in context
oc.Channel = "SIP/trunk/yyyy"; // the agent's channel
oc.Timeout = 30000;
oc.Async = true;
ManagerResponse originateResponse = amiConn.SendAction(oc, oc.Timeout);
```
See https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerAction_Originate for more information about the `Originate` AMI action.

If it doesn't work, it might be an issue on your PBX server, in which case you might get better help if you ask the Asterisk community.

**Closed as completed** 2021-12-18 16:42 UTC
Labels: question
