### ISSUE TITLE
ManagerConnection.IsConnected() always true in event ConnectionState

### ISSUE THREAD

**Issue by GolDiV** [AsterNET/AsterNET#275] opened 2023-06-21 03:09 UTC
I have next part of the code:
```
using AsterNET.Manager;
using AsterNET.Manager.Event;

private ManagerConnection manager;
private bool StartManager()
        {
            manager = new(
                Properties.Resources.amiAddress,
                Int32.Parse(Properties.Resources.amiPort),
                Properties.Resources.amiLogin,
                Properties.Resources.amiPass
                );
            manager.ConnectionState += new ConnectionStateEventHandler(ConnectionState);

            try
            {
                manager.Login();
                return true;
            }
            catch
            {
                return false;
            }
        }

private void ConnectionState(object sender, ConnectionStateEvent e)
        {
            if (manager.IsConnected())
            {
                
                MessageBox.Show("on");
                notifyIcon1.Icon = Properties.Resources.phone_on;
            }
            else
            {
                
                MessageBox.Show("off");
                notifyIcon1.Icon = Properties.Resources.phone_off;
            }
        }
```
Asterisk is in the local net. When I break the connection (pull out the cable), manager.IsConnected() is true, but must be false. I don't understand this behavior. How can I check connection?
And the most interesting thing is if I add a manual status check like this:
```
private void button1_Click(object sender, EventArgs e)
        {
            MessageBox.Show(manager.IsConnected().ToString());
        }
```
then everything is displayed correctly. When there is a connection, it shows true; when there is no connection, it is false.

**Comment by Deantwo** [comment] 2023-06-22 20:34
Duplicate of #150

**Comment by GolDiV** [comment] 2023-06-23 04:34
I seem to have found a particular solution for my case. The fact is that it seems that when the ConnectionStateEvent event fires, the state of the ConnectionManager does not change immediately. Why this happens I did not understand. But when adding a delay, the IsConnected method began to work correctly. 
```
private async void Connection_State(object sender, ConnectionStateEvent e)
        {
            await Task.Delay(1000);
            MessageBox.Show(manager.IsConnected().ToString());
            if (manager.IsConnected())
            {
                notifyIcon1.Icon = Properties.Resources.phone_on;
            }
            else
            {
                notifyIcon1.Icon = Properties.Resources.phone_off;
            }
        }
  ```

**Comment by Deantwo** [comment] 2023-06-23 22:49
Don't use `IsConnected` ([ManagerConnection.cs#L1955](https://github.com/AsterNET/AsterNET/blob/82724c1228d4c5c7e0b21b7fa9d29f7199d2b428/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L1955)), it just checks the state of the underlaying TCP socket, which doesn't reflect the actual AMI state.

Basically, read some of the things discussed in #150 and maybe look at the source code.

**Comment by Deantwo** [comment] 2023-06-23 22:55
If I remember on monday, I can look at shat I did in my project. But I think mainly I just catch the `SystemException`, monitor the `ConnectionStateEvent` and set `ReconnectRetryMax` to `int.MaxVlue`.

**Comment by Deantwo** [comment] 2023-06-27 09:14
You need to check the type of the returned `ConnectionStateEvent` object. The type is what you use to determine the current state of the connection.
For example, try this in your code:
```C#
if (e is ConnectEvent) 
    notifyIcon1.Icon = Properties.Resources.phone_on;
else
    notifyIcon1.Icon = Properties.Resources.phone_off;
```
There are 4 types that inherit from [`ConnectionStateEvent`](https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/Event/ConnectionStateEvent.cs) in total; [`ConnectEvent`](https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/Event/ConnectEvent.cs), [`DisconnectEvent`](https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/Event/DisconnectEvent.cs), [`ReloadEvent`](https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/Event/ReloadEvent.cs), and [`ShutdownEvent`](https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/Event/ShutdownEvent.cs). I am not entirely sure when and how often these events happen, the AMI documentation might say more about this. Such as: I don't know if a `ConnectEvent` follows after a `ReloadEvent`, or if you can assume that `ReloadEvent` means that the connection didn't drop.
On top of that, there is the [`Reconnect`](https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/Event/ConnectionStateEvent.cs#L12) property, which will let you know if the connection is going to attempt to reconnect or if it has given up. Some of the types have other properties that you can use to see why a reload or shutdown happened.

Here is my code:
```C#
    _ami = new ManagerConnection();
    _ami.ConnectionState += Monitoring_ConnectionState;

private void Monitoring_ConnectionState(object sender, ConnectionStateEvent e)
{
    if (e is null)
        throw new ArgumentNullException(nameof(e));

    switch (e)
    {
        case ConnectEvent e1:
            System.Diagnostics.Debug.WriteLine($"{nameof(ConnectEvent)}: {e1}");
            break;
        case DisconnectEvent e2:
            System.Diagnostics.Debug.WriteLine($"{nameof(DisconnectEvent)}: {e2}");
            break;
        case ReloadEvent e3:
            System.Diagnostics.Debug.WriteLine($"{nameof(ReloadEvent)}: {e3}");
            break;
        case ShutdownEvent e4:
            System.Diagnostics.Debug.WriteLine($"{nameof(ShutdownEvent)}: {e4}");
            break;
        default: // Should only be the 4 ConnectionState event types, but just to be sure.
            System.Diagnostics.Debug.WriteLine($"Unknown {nameof(ConnectionStateEvent)}: {e}");
            break;
    }
}
```
As mentioned in #150, the connection state is weirdly conveyed in AsterNET, that part could really use a rewrite. Or at least a guide and example on how to use it, but I guess this post will work for now.

**Comment by GolDiV** [comment] 2023-06-29 05:30
Ок, its fine. Thank you!

**Closed as completed** 2023-06-29 05:30 UTC
