### ISSUE TITLE
Passing multiple variables

### ISSUE THREAD

**Issue by elmar69** [AsterNET/AsterNET#202] opened 2019-06-11 15:37 UTC
On Passing multiple Variables values and Names are all passed into an single Variable.

setting `VAR_DELIMITER = "\nVariable: ".ToCharArray();` does help and sould describe problem detail.

**Comment by Deantwo** [comment] 2019-06-11 17:23
A code example showing what you are sending, and an example of what exactly the Asterisk server is replying would be useful.

**Comment by Deantwo** [comment] 2019-10-10 13:08
`VAR_DELIMITER` is assigned in the [`determineVersion()`](https://github.com/AsterNET/AsterNET/blob/2428cc1e8b4b01f1b58b58cd125f6865d3077ca1/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L991) method.
If you set `VAR_DELIMITER` to an array that like it would likely totally chop up all replies that contain any of those characters.

So what is your issue?
Need an example of what you are trying do it.

**Comment by Deantwo** [comment] 2020-02-06 08:18
This might be fixed with #221.

**Comment by Deantwo** [comment] 2020-02-06 12:09
@elmar69 can you confirm that this issue is the same as explained in #220?

**Comment by elmar69** [comment] 2020-02-06 13:46
#220 does describe the same problem, the workaround told on SO does fix the same problem as what I did mention above.

**Comment by Deantwo** [comment] 2021-04-21 14:01
Duplicate of #220

**Closed** 2021-04-21 14:01 UTC
Labels: not enough information
